### ISSUE TITLE
Can we include video links in README

### ISSUE THREAD

**Issue by nayabatir1** [saiyam1814/DevOpsRoadmap2022#138]
All the video links mentioned in the youtube video description can we add it on README, it would be very convenient.

**Comment by kranurag7** [comment]
@nayabatir1 we can include that. I am also creating a syllabus and CONTRIBUTING.md file. Let me know if you have any further suggestions.

**Comment by nayabatir1** [comment]
> @nayabatir1 we can include that. I am also creating a syllabus and CONTRIBUTING.md file. Let me know if you have any further suggestions. 

Sure

**Comment by kranurag7** [comment]
@nayabatir1 We have implemented the suggestions. I am closing this issue now. Feel free to raise new Issue again if you have some suggestions for the repo.
