### ISSUE TITLE
Introducing some workflows via github-action

### ISSUE THREAD

**Issue by kranurag7** [saiyam1814/DevOpsRoadmap2022#160]
@saiyam1814 Should we include some github workflows in our repository. 
We can include some workflows that will trigger based on events like new issue, pull request and fork. This is mainly to encourage new contributors.
Learners can see and understand github actions if they want. I think this will be a great introduction to CI/CD for them. They can also inspect what's going on in the actions tab. 
I am also thinking of creating a workflow that will lint the go source code that's available in the repository.

**Comment by saiyam1814** [comment]
YEs we can do that via github actions, 
I am thinking to prepare notes and assignments for each topic and then videos of our own in detail that leads to professional world!

**Comment by kranurag7** [comment]
Should I start working on this? Please let me know if it will be useful for the repository?

**Comment by nayabatir1** [comment]
> YEs we can do that via github actions, I am thinking to prepare notes and assignments for each topic and then videos of our own in detail that leads to professional world!

excited for the assignments.

**Comment by saiyam1814** [comment]
Yes @kranurag7 you can work on the github actions , it should be simple - check this video for better understanding https://youtu.be/eooi60Mks_0

**Comment by saiyam1814** [comment]
@nayabatir1 I am thinking of how we can do this for each module so that people can understand learn and do some hands on as well. Also we need to keep pushing people to share and learn together so that we have thousands of people learning together. 
Encourage people to join discord and they will have me with them on this whole journey!

**Comment by kranurag7** [comment]
@saiyam1814 I'm confused about what type of workflows should I bring? One simple option can be linting but I have checked the `super-linter` and it was failing on go code in my personal repo.
@nayabatir1 and @Nejilee Any suggestions?

**Comment by kranurag7** [comment]
Okay @nayabatir1 I'm putting this issue on hold as of now. I'm closing this issue.
