### ISSUE TITLE
doubt related to docker

### ISSUE THREAD

**Issue by nayabatir1** [saiyam1814/DevOpsRoadmap2022#244]
>Before we move ahead though, let's quickly talk about deleting containers. We saw above that we can still see remnants of the container even after we've exited by running docker ps -a. Throughout this tutorial, you'll run docker run multiple times and leaving stray containers will eat up disk space. Hence, as a rule of thumb, I clean up containers once I'm done with them. To do that, you can run the docker rm command. Just copy the container IDs from above and paste them alongside the command.

@saiyam1814 I was reading [this](https://docker-curriculum.com/#:~:text=Before%20we%20move,alongside%20the%20command.) article. Can you please verify is above statement correct?

if it is correct then how is it possible I exited my container and `docker ps` shows no container running at the moment.

**Comment by kranurag7** [comment]
@nayabatir1 I think the statement is correct. When you are using `docker ps` command then it will only show the containers that are in running state. On the other hand, `docker ps -a` will show you all the containers (running and exited).

**Comment by nayabatir1** [comment]
You mean to say if I exit the container then it's not running. 
If it's not running then why it is consuming resources.

**Comment by kranurag7** [comment]
Just for analogy, think of the any application running in your phone. Even if the app is closed, it's still consuming the resources.

**Comment by saiyam1814** [comment]
Hello - Docker ps -a -> Gives a list of all the containers, they will be there in `/var/lib/docker`. So the filesystem state will be preserved but the process will be killed so now memory resources will be consumed. 
Docker ps -> Active containers which consume cpu/memory
This gives a more detailed explanation - https://stackoverflow.com/questions/27799282/resource-usage-by-stopped-docker-containers
